# AUTO-GENERATED by AI Agent using Gemini
# Source: UserStories/US2.md

import math

def calculate_emi(principal: float, annual_interest_rate: float, tenure_years: int) -> float:
    """
    Calculates the Equated Monthly Installment (EMI) for a loan.

    Args:
        principal (float): The total principal loan amount.
        annual_interest_rate (float): The annual interest rate as a percentage (e.g., 8.5 for 8.5%).
        tenure_years (int): The loan tenure in years.

    Returns:
        float: The calculated monthly EMI.

    Raises:
        ValueError: If principal, annual_interest_rate, or tenure_years are invalid.
    """
    if not isinstance(principal, (int, float)) or principal <= 0:
        raise ValueError("Principal must be a positive number.")
    if not isinstance(annual_interest_rate, (int, float)) or annual_interest_rate < 0:
        raise ValueError("Annual interest rate cannot be negative.")
    if not isinstance(tenure_years, int) or tenure_years <= 0:
        raise ValueError("Tenure in years must be a positive integer.")

    monthly_interest_rate = (annual_interest_rate / 100) / 12
    tenure_months = tenure_years * 12

    if monthly_interest_rate == 0:
        # If interest rate is 0, EMI is simply principal / number of months
        emi = principal / tenure_months
    else:
        # EMI formula: P * R * (1 + R)^N / ((1 + R)^N - 1)
        # Where P = Principal, R = Monthly Interest Rate, N = Tenure in Months
        power_term = (1 + monthly_interest_rate)**tenure_months
        numerator = principal * monthly_interest_rate * power_term
        denominator = power_term - 1
        
        # This check should ideally not be hit with valid positive inputs for rate and tenure.
        if denominator == 0:
            raise ValueError("Cannot calculate EMI due to an invalid combination of interest rate and tenure.")
            
        emi = numerator / denominator

    return emi


if __name__ == "__main__":
    try:
        print("--- Loan EMI Calculator ---")
        
        loan_principal_input = input("Enter principal loan amount (e.g., 100000): ")
        annual_rate_input = input("Enter annual interest rate as a percentage (e.g., 8.5 for 8.5%): ")
        loan_tenure_years_input = input("Enter loan tenure in years (e.g., 5): ")

        principal = float(loan_principal_input)
        annual_rate = float(annual_rate_input)
        tenure_years = int(loan_tenure_years_input)

        monthly_emi = calculate_emi(principal, annual_rate, tenure_years)
        
        print("\n--- Loan Details ---")
        print(f"Principal Amount: ${principal:,.2f}")
        print(f"Annual Interest Rate: {annual_rate:.2f}%")
        print(f"Loan Tenure: {tenure_years} years")
        print("\n--- Calculation Result ---")
        print(f"Your Monthly EMI will be: ${monthly_emi:,.2f}")

    except ValueError as e:
        print(f"Input Error: {e}. Please ensure you enter valid numerical data.")
    except Exception as e:
        print(f"An unexpected error occurred: {e}")