# AUTO-GENERATED by AI Agent using Gemini
# Source: UserStories/US2.md

import math

def calculate_emi(principal: float, annual_interest_rate: float, tenure_in_years: float) -> float:
    """
    Calculates the Equated Monthly Installment (EMI) for a loan.

    The EMI formula used is:
    EMI = [P * R * (1 + R)^N] / [(1 + R)^N – 1]
    Where:
    P = Principal loan amount
    R = Monthly interest rate (annual_interest_rate / 12 / 100)
    N = Loan tenure in months (tenure_in_years * 12)

    Args:
        principal: The total loan amount. Must be a positive number.
        annual_interest_rate: The annual interest rate in percentage (e.g., 8.5 for 8.5%). Must be non-negative.
        tenure_in_years: The loan tenure in years. Must be a positive number.

    Returns:
        The calculated monthly EMI.

    Raises:
        ValueError: If any input is invalid (non-positive principal, negative rate, non-positive tenure).
    """
    if not isinstance(principal, (int, float)) or principal <= 0:
        raise ValueError("Principal must be a positive number.")
    if not isinstance(annual_interest_rate, (int, float)) or annual_interest_rate < 0:
        raise ValueError("Annual interest rate must be a non-negative number.")
    if not isinstance(tenure_in_years, (int, float)) or tenure_in_years <= 0:
        raise ValueError("Tenure in years must be a positive number.")

    # Convert annual interest rate percentage to monthly decimal rate
    # e.g., 8.5% becomes 0.085 annually, then 0.085/12 monthly
    monthly_interest_rate = annual_interest_rate / (12 * 100)
    
    # Convert tenure in years to total number of monthly payments
    number_of_payments = tenure_in_years * 12

    if monthly_interest_rate == 0:
        # Special case for 0% interest: EMI is simply Principal / N
        emi = principal / number_of_payments
    else:
        # Standard EMI formula calculation
        power_factor = (1 + monthly_interest_rate) ** number_of_payments
        numerator = principal * monthly_interest_rate * power_factor
        denominator = power_factor - 1
        emi = numerator / denominator

    return emi

def _get_float_input(prompt: str, min_value: float = None, allow_zero: bool = False) -> float:
    """
    Helper function to get validated float input from the user.
    """
    while True:
        try:
            value_str = input(prompt).strip()
            value = float(value_str)
            if min_value is not None and value < min_value:
                print(f"Error: Value must be at least {min_value}.")
                continue
            if not allow_zero and value == 0:
                print("Error: Value cannot be zero. Please enter a positive number.")
                continue
            return value
        except ValueError:
            print("Error: Invalid input. Please enter a valid number.")

if __name__ == "__main__":
    print("--- Loan EMI Calculator ---")
    print("Enter the details below to calculate your monthly EMI.")

    try:
        principal = _get_float_input("Enter the principal loan amount (e.g., 100000): ", min_value=0.01)
        annual_interest_rate = _get_float_input("Enter the annual interest rate in percentage (e.g., 8.5): ", min_value=0.0, allow_zero=True)
        tenure_in_years = _get_float_input("Enter the loan tenure in years (e.g., 5 for 5 years): ", min_value=0.01)

        emi_result = calculate_emi(principal, annual_interest_rate, tenure_in_years)

        print("\n--- Calculation Result ---")
        print(f"Principal Loan Amount: {principal:,.2f}")
        print(f"Annual Interest Rate: {annual_interest_rate:.2f}%")
        print(f"Loan Tenure: {tenure_in_years:.0f} years ({int(tenure_in_years * 12)} months)")
        print(f"Your Monthly EMI: {emi_result:,.2f}")

    except ValueError as e:
        print(f"\nAn error occurred: {e}")
    except Exception as e:
        print(f"\nAn unexpected error occurred: {e}")
    finally:
        # AC2: Application should delete the customer data after customer close the application
        # For a command-line script, user input data is stored only in temporary variables
        # in memory. It is automatically discarded when the script finishes execution,
        # ensuring no persistence of customer data.
        print("\nThank you for using the EMI Calculator. Your data has not been stored.")